export enum AnalyticsEvent {
  // Authentication
  SignedUp = 'Signed Up',
  SignedIn = 'Signed In',

  // Publications
  PublicationCreated = 'Publication Created',
  PublicationDeleted = 'Publication Deleted',
  PublicationSettingsUpdated = 'Publication Settings Updated',
  PublicationTemplateChanged = 'Publication Template Changed',
  PublicationStyleChanged = 'Publication Style Changed',

  // Topics
  TopicCreated = 'Topic Created',
  TopicUpdated = 'Topic Updated',
  TopicDeleted = 'Topic Deleted',
  TopicToggled = 'Topic Toggled',

  // Content Scout
  ScoutTriggered = 'Scout Triggered',
  ScoutScheduleUpdated = 'Scout Schedule Updated',
  ScoutAutomationToggled = 'Scout Automation Toggled',

  // Ideas
  IdeasFiltered = 'Ideas Filtered',
  IdeaReviewed = 'Idea Reviewed',
  IdeaPromoted = 'Idea Promoted',
  IdeaDismissed = 'Idea Dismissed',

  // Writing Sessions
  SessionCreated = 'Session Created',
  SessionOpened = 'Session Opened',
  SessionDeleted = 'Session Deleted',

  // Chat / AI
  ChatMessageSent = 'Chat Message Sent',
  ChatGenerationStopped = 'Chat Generation Stopped',

  // Drafts
  DraftCreated = 'Draft Created',
  DraftEdited = 'Draft Edited',
  DraftCopied = 'Draft Copied',

  // Image Generation
  ImageGenerationStarted = 'Image Generation Started',
  ImageSelected = 'Image Selected',

  // Publishing
  PublishModalOpened = 'Publish Modal Opened',
  PostPublished = 'Post Published',
  LinkedInPostPublished = 'LinkedIn Post Published',
  TwitterPostPublished = 'Twitter Post Published',
  PublishFailed = 'Publish Failed',

  // SEO / AI Assists
  SeoAutoGenerated = 'SEO Auto Generated',
  TweetAutoGenerated = 'Tweet Auto Generated',
  LinkedInOptimized = 'LinkedIn Optimized',

  // Writing Styles
  StyleCreated = 'Style Created',
  StyleUpdated = 'Style Updated',
  StyleDuplicated = 'Style Duplicated',
  StyleDeleted = 'Style Deleted',

  // Custom Domains
  CustomDomainConnectStarted = 'Custom Domain Connect Started',
  CustomDomainConnectSucceeded = 'Custom Domain Connect Succeeded',
  CustomDomainConnectFailed = 'Custom Domain Connect Failed',
  CustomDomainActivated = 'Custom Domain Activated',
  CustomDomainRemoved = 'Custom Domain Removed',
  CustomDomainCheckStatus = 'Custom Domain Check Status',

  // Social Connections
  SocialConnected = 'Social Connected',
  SocialDisconnected = 'Social Disconnected',

  // RSS
  FeedToggled = 'Feed Toggled',

  // Onboarding
  ChecklistStepCompleted = 'Checklist Step Completed',
  ChecklistDismissed = 'Checklist Dismissed',

  // Navigation
  PageViewed = 'Page Viewed',
}

export interface AnalyticsEventProperties {
  // Authentication
  [AnalyticsEvent.SignedUp]: { method: string }
  [AnalyticsEvent.SignedIn]: { method: string }

  // Publications
  [AnalyticsEvent.PublicationCreated]: { publicationId: string; name: string; source: string }
  [AnalyticsEvent.PublicationDeleted]: { publicationId: string }
  [AnalyticsEvent.PublicationSettingsUpdated]: { publicationId: string; field: string }
  [AnalyticsEvent.PublicationTemplateChanged]: { publicationId: string; templateId: string; templateName: string }
  [AnalyticsEvent.PublicationStyleChanged]: { publicationId: string; styleId: string; styleName: string }

  // Topics
  [AnalyticsEvent.TopicCreated]: { publicationId: string; source: string }
  [AnalyticsEvent.TopicUpdated]: { publicationId: string }
  [AnalyticsEvent.TopicDeleted]: { publicationId: string }
  [AnalyticsEvent.TopicToggled]: { publicationId: string; active: boolean }

  // Content Scout
  [AnalyticsEvent.ScoutTriggered]: { publicationId: string; source: string }
  [AnalyticsEvent.ScoutScheduleUpdated]: { publicationId: string; scheduleType: string; publishMode: string }
  [AnalyticsEvent.ScoutAutomationToggled]: { publicationId: string; enabled: boolean }

  // Ideas
  [AnalyticsEvent.IdeasFiltered]: { publicationId: string; filter: string }
  [AnalyticsEvent.IdeaReviewed]: { publicationId: string }
  [AnalyticsEvent.IdeaPromoted]: { publicationId: string }
  [AnalyticsEvent.IdeaDismissed]: { publicationId: string }

  // Writing Sessions
  [AnalyticsEvent.SessionCreated]: { publicationId: string; source: string }
  [AnalyticsEvent.SessionOpened]: Record<string, never>
  [AnalyticsEvent.SessionDeleted]: Record<string, never>

  // Chat / AI
  [AnalyticsEvent.ChatMessageSent]: { messageLength: number }
  [AnalyticsEvent.ChatGenerationStopped]: Record<string, never>

  // Drafts
  [AnalyticsEvent.DraftCreated]: { draftVersion: number; source: string }
  [AnalyticsEvent.DraftEdited]: { draftVersion: number }
  [AnalyticsEvent.DraftCopied]: { draftVersion: number }

  // Image Generation
  [AnalyticsEvent.ImageGenerationStarted]: { promptSource: string }
  [AnalyticsEvent.ImageSelected]: Record<string, never>

  // Publishing
  [AnalyticsEvent.PublishModalOpened]: { isUpdate: boolean }
  [AnalyticsEvent.PostPublished]: { publicationId: string; isUpdate: boolean; hasLinkedIn: boolean; hasTwitter: boolean; hasFeaturedImage: boolean }
  [AnalyticsEvent.LinkedInPostPublished]: { publicationId: string; postMode: string; usedAiOptimize: boolean }
  [AnalyticsEvent.TwitterPostPublished]: { publicationId: string; usedAiGenerate: boolean; tweetLength: number }
  [AnalyticsEvent.PublishFailed]: { platform: string; error: string }

  // SEO / AI Assists
  [AnalyticsEvent.SeoAutoGenerated]: Record<string, never>
  [AnalyticsEvent.TweetAutoGenerated]: Record<string, never>
  [AnalyticsEvent.LinkedInOptimized]: { postMode: string }

  // Writing Styles
  [AnalyticsEvent.StyleCreated]: { styleId: string; method: string }
  [AnalyticsEvent.StyleUpdated]: { styleId: string }
  [AnalyticsEvent.StyleDuplicated]: { sourceStyleId: string; newStyleId: string }
  [AnalyticsEvent.StyleDeleted]: { styleId: string; isPrebuilt: boolean }

  // Custom Domains
  [AnalyticsEvent.CustomDomainConnectStarted]: { publicationId: string; domain: string }
  [AnalyticsEvent.CustomDomainConnectSucceeded]: { publicationId: string; domain: string }
  [AnalyticsEvent.CustomDomainConnectFailed]: { publicationId: string; domain: string; error: string }
  [AnalyticsEvent.CustomDomainActivated]: { publicationId: string; domain: string }
  [AnalyticsEvent.CustomDomainRemoved]: { publicationId: string; domain: string }
  [AnalyticsEvent.CustomDomainCheckStatus]: { publicationId: string; domain: string; status: string }

  // Social Connections
  [AnalyticsEvent.SocialConnected]: { provider: string }
  [AnalyticsEvent.SocialDisconnected]: { provider: string }

  // RSS
  [AnalyticsEvent.FeedToggled]: { publicationId: string; feedType: string; enabled: boolean }

  // Onboarding
  [AnalyticsEvent.ChecklistStepCompleted]: { publicationId: string; step: string }
  [AnalyticsEvent.ChecklistDismissed]: { publicationId: string; completedSteps: number }

  // Navigation
  [AnalyticsEvent.PageViewed]: { path: string; pageName?: string }
}
