// The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
// We extend it here with secrets and typed bindings that wrangler doesn't know about

import type { DataLayerApi } from '@hotmetal/data-layer'

export interface NotificationsEnv extends Omit<Env, 'DAL' | 'FROM_EMAIL' | 'WELCOME_FROM_EMAIL' | 'WEB_APP_URL'> {
  // Data Access Layer (overrides base Fetcher with typed RPC interface)
  DAL: DataLayerApi

  // Non-secret env vars
  FROM_EMAIL: string
  WELCOME_FROM_EMAIL?: string
  WEB_APP_URL: string

  // Secrets (set via `wrangler secret put`)
  RESEND_API_KEY: string
  API_KEY: string

  // Axiom logging (optional — falls back to console-only when not set)
  AXIOM_TOKEN?: string
  AXIOM_DATASET?: string
}
