// The base Env is generated by `wrangler types` (worker-configuration.d.ts).
// Here we narrow the service/workflow bindings to their typed interfaces.
import type { DataLayerApi } from '@hotmetal/data-layer'

// `Workflow`, `Fetcher` are global runtime types (from worker-configuration.d.ts)
// — not module imports. TENANT_INVOKER is a plain Fetcher service binding.

export interface ProvisionerEnv extends Omit<Env, 'DAL' | 'PROVISION_WORKFLOW'> {
	/** Data Access Layer (typed RPC over the service binding). */
	DAL: DataLayerApi
	/** The provisioning workflow binding. */
	PROVISION_WORKFLOW: Workflow<ProvisionWorkflowParams>

	// Secrets (set via `wrangler secret put`; not known to `wrangler types`).
	CF_API_TOKEN: string
	/** Authenticates incoming /api requests (web → provisioner). */
	API_KEY: string
	AXIOM_TOKEN?: string
	/**
	 * Turnstile secret for tenant comment-submit bot verification — injected into
	 * each tenant script as a `secret_text` binding so EmDash comments work fleet-wide.
	 */
	TURNSTILE_SECRET_KEY?: string

	/**
	 * Public Turnstile site key (from `vars`) — injected into each tenant as a
	 * plain var so the comment form widget renders. Same key used by
	 * publications-web + the single-instance emdash-blog across *.hotmetalapp.com.
	 */
	TURNSTILE_SITE_KEY?: string
}

/** Input to a single tenant-provision run. */
export interface ProvisionWorkflowParams {
	/** The publication this EmDash instance belongs to. */
	publicationId: string
	/** The publication slug — drives the default hostname + PUBLICATION_SLUG var. */
	slug: string
	/** What kicked this off (for logs / idempotency reasoning). */
	triggeredBy: 'create' | 'manual' | 'retry'
}

/**
 * JSON shape stored in `publications.cms_instance_meta` — everything needed to
 * operate or tear down a provisioned instance.
 */
export interface CmsInstanceMeta {
	/** Dispatch-namespace script name (== tenant id). */
	scriptName: string
	/** Per-tenant D1 database id. */
	d1DatabaseId: string
	d1DatabaseName: string
	/** Per-tenant R2 media bucket name. */
	r2BucketName: string
	/** Per-tenant KV namespace id for EmDash sessions. */
	kvNamespaceId: string
	/** The hostname the instance serves on. */
	hostname: string
	/** Cloudflare for SaaS custom-hostname id (for status/teardown). */
	cfHostnameId?: string
	/** The bundle release version this tenant was provisioned from. */
	bundleVersion: string
	/** ISO timestamp the instance reached `ready`. */
	provisionedAt?: string
}

/**
 * Parse `publications.cms_instance_meta` (a JSON string) into `CmsInstanceMeta`.
 * Returns null for missing OR malformed JSON, so callers degrade gracefully (e.g.
 * teardown falls back to deriving resource names) instead of throwing.
 */
export function parseCmsInstanceMeta(raw: string | null | undefined): CmsInstanceMeta | null {
	if (!raw) return null
	try {
		return JSON.parse(raw) as CmsInstanceMeta
	} catch {
		return null
	}
}
