// The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
// We extend it here with secrets and typed bindings that wrangler doesn't know about

import type { DataLayerApi } from '@hotmetal/data-layer'

export interface ScoutEnv extends Omit<Env, 'DAL'> {
  // Data Access Layer (overrides base Fetcher with typed RPC interface)
  DAL: DataLayerApi

  // Service binding to web worker (for auto-write pipeline)
  WEB: Fetcher

  // Secrets (set via `wrangler secret put`)
  API_KEY: string
  ALEXANDER_API_KEY: string
  ANTHROPIC_API_KEY: string
  INTERNAL_API_KEY: string
}

export interface ScoutQueueMessage {
  publicationId: string
  triggeredBy: 'cron' | 'manual'
}

export interface ScoutWorkflowParams {
  publicationId: string
  triggeredBy: 'cron' | 'manual'
}
