// The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
// We extend it here with secrets and typed bindings that wrangler doesn't know about

import type { DataLayerApi } from '@hotmetal/data-layer'

export interface NotificationsApi {
  sendNewIdeasNotification(params: { userId: string; publicationName: string; ideasCount: number }): Promise<void>
  sendDraftReadyNotification(params: { userId: string; publicationName: string; postTitle: string }): Promise<void>
  sendPostPublishedNotification(params: { userId: string; publicationName: string; postTitle: string; postUrl: string }): Promise<void>
  sendNewCommentNotification(params: { userId: string; publicationName: string; postSlug: string; commenterName: string; commentPreview: string; postUrl: string }): Promise<void>
}

export interface ScoutEnv extends Omit<Env, 'DAL' | 'NOTIFICATIONS' | 'PUBLICATIONS_BASE_DOMAIN'> {
  // Data Access Layer (overrides base Fetcher with typed RPC interface)
  DAL: DataLayerApi

  // Notifications service (overrides base Fetcher with typed RPC interface)
  NOTIFICATIONS: NotificationsApi

  // Service binding to web worker (for auto-write pipeline)
  WEB: Fetcher

  // Non-secret env vars
  PUBLICATIONS_BASE_DOMAIN: string

  // Secrets (set via `wrangler secret put`)
  API_KEY: string
  ALEXANDER_API_KEY: string
  ANTHROPIC_API_KEY: string
  INTERNAL_API_KEY: string

  // Wilson LLM usage tracking (optional — tracking disabled if missing)
  WILSON_API_URL?: string
  WILSON_API_KEY?: string
}

export interface ScoutQueueMessage {
  publicationId: string
  triggeredBy: 'cron' | 'manual'
}

export interface ScoutWorkflowParams {
  publicationId: string
  triggeredBy: 'cron' | 'manual'
}
