// The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
// We extend it here with secrets that wrangler doesn't know about

export interface ScoutEnv extends Env {
  // Secrets (set via `wrangler secret put`)
  API_KEY: string
  ALEXANDER_API_KEY: string
  ANTHROPIC_API_KEY: string
  WRITER_AGENT_API_KEY: string
}

export interface ScoutQueueMessage {
  publicationId: string
  triggeredBy: 'cron' | 'manual'
}

export interface ScoutWorkflowParams {
  publicationId: string
  triggeredBy: 'cron' | 'manual'
}
